image: node:10.15.3

pipelines:
  branches:
    prod:
      - step:
          name: 'Build front'
          caches:
            - node
          script:
            - cd front
            - npm install 
            - npm install -g @angular/cli 
            - ng build --prod   
            - cd ../back
            - echo "$(ls public/)"
            - cd ../
          artifacts:
            - back/**
      - step:
          name: 'Create zip'
          script:
            - tar czfv application.tgz back
          artifacts:
            - application.tgz
      - step:
          name: 'Deploy to Heroku in production'
          deployment: production
          script:
            - pipe: atlassian/heroku-deploy:0.1.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: $HEROKU_APP_NAME
                ZIP_FILE: "application.tgz"